package de.unifrankfurt.informatik.linkedopendata.model;

import java.util.HashMap;

public class Abbreviations {
	
	@SuppressWarnings("serial")
	public final HashMap<String, String> map = new HashMap<String, String>() {{
	    put("ä.", "ähnlich");
	    put("a.", "Adjektiv");
	    put("acc.", "Akkusativ");
	    put("acymr.", "altcymrisch");
	    put("dän.", "dänisch");
	    put("adän.", "altdänisch");
	    put("adj", "Adjektiv");
	    put("adv.", "Adverb");
	    put("aeol.", "aeolisch");
	    put("afr.", "altfranzösisch");
	    put("afränk.", "altfränkisch");
	    put("afries.", "altfriesisch");
	    put("ags.", "Angelsächsisch");
	    put("ahd.", "Althochdeutsch");
	    put("air.", "altirisch");
	    put("akk.", "Akkusativ");
	    put("alb.", "albanisch");
	    put("altfries.", "altfriesisch");
	    put("altir.", "altirisch");
	    put("altlat.", "altlateinisch");
	    put("amhd.", "alt-");
	    put("an.", "altnordisch");
	    put("OIcel.", "Old Norse (i.e. Old Icelandic)");
	    put("and.", "altniederdeutsch");
	    put("angl.", "anglisch");
	    put("aor.", "Aorist");
	    put("apers.", "altpersisch");
	    put("arm.", "armenisch");
	    put("as.", "altsächsisch");
	    put("aschw.", "altschwedisch");
	    put("aschwed.", "altschwedisch");
	    put("asl.", "altkirchenslawisch");
	    put("OSlav.", "Old Slavic");
	    put("bair.", "bairisch");
	    put("Bav.", "Bavarian");
	    put("bes.", "besonders");
	    put("bulg.", "bulgarisch");
	    put("c.", "cum");
	    put("caus.", "Kausativ");
	    put("causat.", "Kausativ");
	    put("comp.", "Komparativ");
	    put("compar.", "Komparativ");
	    put("conj.", "Konjunktion");
	    put("cymr.", "cymrisch");
	    put("dat.", "dative");
	    put("d.", "Dativ, deutsch, der");
	    put("d.h.", "das heißt");
	    put("i.e.", "that is, namely");
	    put("dän.", "dänisch");
	    put("dan.", "Danish");
	    put("dass.", "dasselbe");
	    put("dat.", "Dativ");
	    put("denom.", "denominal");
	    put("d.", "i.");
	    put("dial.", "dialektal");
	    put("dim.", "Diminutiv");
	    put("dimin.", "Diminutiv");
	    put("dissim.", "dissimilierend");
	    put("dor.", "dorisch");
	    put("eig.", "eigentlich");
	    put("eigentl.", "eigentlich");
	    put("eigtl.", "eigentlich");
	    put("engl.", "englisch");
	    put("ModE.", "English");
	    put("etw.", "etwas");
	    put("f.", "feminin");
	    put("fem.", "feminin");
	    put("finn.", "finnisch");
	    put("fl.", "flektiert");
	    put("fläm.", "flämisch");
	    put("fries.", "friesisch");
	    put("Goth.", "Gothic");
	    put("g.", "Genitiv");
	    put("gen.", "genitive");
	    put("gael.", "gaelisch");
	    put("gall.", "altgall.");
	    put("gen.", "Genitiv");
	    put("germ.", "germanisch");
	    put("Germ.", "Germanic");
	    put("german.", "germanisch");
	    put("got.", "gotisch");
	    put("Goth.", "Gothic");
	    put("gr.", "Griechisch");
	    put("Gk.", "Greek");
	    put("griech.", "Griechisch");
	    put("Grundwz.", "Grundwurzel");
	    put("hess.", "hessisch");
	    put("Hesych.", "Hesychios");
	    put("i.", "in");
	    put("idg.", "indogermanisch");
	    put("ig.", "indogermanisch");
	    put("instr.", "Instrumental");
	    put("intens.", "Intensivum");
	    put("intr.", "intransitiv");
	    put("ion.", "ionisch");
	    put("ir.", "irisch");
	    put("isl.", "isländisch");
	    put("jmd.", "jemand");
	    put("kelt.", "keltisch");
	    put("klruss.", "kleinrussisch");
	    put("kret.", "kretisch");
	    put("langob.", "langobardisch");
	    put("lat.", "lateinisch");
	    put("Lat.", "Latin");
	    put("lett.", "lettisch");
	    put("Latv.", "Latvian,");
	    put("lit.", "litauisch");
	    put("Lith.", "Lithuanian");
	    put("loc.", "Lokativ");
	    put("m.", "maskulin");
	    put("m.engl.", "Mittelenglisch");
	    put("md.", "mitteldeutsch");
	    put("mengl.", "Mittelenglisch");
	    put("mhd.", "Mittelhochdeutsch");
	    put("MHG.", "Middle High German");
	    put("mlat.", "mittellatenisch");
	    put("mnd.", "Mittelniederdeutsch");
	    put("MLG.", "Middle Low German");
	    put("mndl.", "Mittelniederländisch");
	    put("MDut.", "Middle Dutch");
	    put("mundartl.", "mundartlich");
	    put("n.", "sächlich");
	    put("nd.", "niederdeutsch");
	    put("ndl.", "niederländisch");
	    put("Dut.", "Dutch");
	    put("Nebenwz.", "Nebenwurzel");
	    put("neuisl.", "neuisländisch");
	    put("neunorw.", "neunorwegisch");
	    put("neupers.", "neupersisch");
	    put("neutr.", "sächlich");
	    put("nfries.", "neufriesisch");
	    put("nhd.", "neuhochdeutsch");
	    put("ModHG.", "Modern High German");
	    put("nnd.", "neuniederdeutsch");
	    put("nndl.", "neuniederländisch");
	    put("nnorw", "Neunorwegisch");
	    put("ModNorw.", "Modern Norwegian");
	    put("nom.", "Nominativ");
	    put("Nord.", "nordisch");
	    put("nordfries.", "nordfriesisch");
	    put("norw.", "norwegisch");
	    put("Norw.", "Norwegian");
	    put("nschwed.", "neuschwedisch");
	    put("nsl.", "nordslawisch");
	    put("nslav.", "nordslawisch");
	    put("nslov.", "neuslowenisch");
	    put("o. ä.", "oder ähnliches");
	    put("oberd.", "oberdeutsch");
	    put("ofries.", "ostfriesisch");
	    put("osk.", "oskisch");
	    put("ostfries.", "ostfriesisch");
	    put("p.", "Person");
	    //put("p.", "polnisch"); -> (?) likely not
	    put("part.", "Partizip");
	    put("partc.", "Partizip");
	    put("part.", "praet.");
	    put("pass.", "passiv");
	    put("perf.", "Perfekt");
	    put("pers.", "Person");
	    put("pl.", "Plural");
	    put("plur.", "Plural");
	    put("poet.", "poetisch");
	    put("poss.", "Possessiv");
	    put("präf.", "Präfix");
	    put("präp.", "Präposition");
	    put("präpos.", "Präposition");
	    put("prät.", "Präteritum");
	    put("praef.", "Präfix");
	    put("praep.", "Präposition");
	    put("praepos.", "Präposition");
	    put("praes.", "Präsens");
	    put("praet.", "Präteritum");
	    put("preuß.", "Preussisch");
	    put("Pruss.", "Prussian");
	    put("preuss.", "Preussisch");
	    put("Pruss.", "Prussian");
	    put("pron.", "Pronomen");
	    put("ptc.", "Partizip");
	    put("red.", "redupliziert");
	    put("redupl.", "redupliziert");
	    put("refl.", "reflexiv");
	    put("rel.", "relativ");
	    put("russ.", "russisch");
	    put("russ.", "Russian");
	    put("s.", "siehe");
	    put("südd.", "süddeutsch");
	    put("sbst.", "Substantive");
	    put("schw.", "schwach");
	    put("schwäb.", "schwäbisch");
	    put("schwed.", "schwedisch");
	    put("Swed.", "Swedish");
	    put("schweiz.", "schweizerdeutsch");
	    put("serb.", "serbisch");
	    put("sg.", "Einzahl");
	    put("skr.", "sanskrit");
	    put("Skt.", "Sanskrit");
	    put("spätmhd.", "spätmittelhochdeutsch");
	    put("st.", "stark");
	    put("subst.", "Substantive");
	    put("sup.", "Superlativ");
	    put("superl.", "Superlativ");
	    put("tirol.", "tirolerisch");
	    put("trans.", "transitiv");
	    put("u. a.", "unter anderem");
	    put("u. dgl." , "und dergleichen");
	    put("u.s.w.", "und so weiter");
	    put("etc.", "et cetera");
	    put("umbr.", "umbrisch");
	    put("unpers.", "unpersönlich");
	    put("urspr.", "ursprünglich");
	    put("ursprüngl.", "ursprünglich");
	    put("v.", "von");
	    put("v. o.", "von oben");
	    put("v. u.", "von unten");
	    put("vb.", "verbum");
	    put("vergl.", "vergleiche");
	    put("cf.", "compare");
	    put("vgl.", "vergleiche");
	    put("cf.", "compare");
	    put("westfäl.", "westfälisch");
	    put("westfläm.", "westflämisch");
	    put("westgerm.", "westgermanisch");
	    put("WGmc.", "West Germanic");
	    put("wfries.", "westfriesisch");
	    put("Wz.", "Wurzel");
	    put("z.B.", "zum");
	    put("e. g.", "for example");
	    put("zend.", "zendisch");
	    put("Av.", "Avestan");
	}};

}
